services:
  araozu_dev:
    image: nginx:alpine
    restart: unless-stopped
    container_name: dev_araozu
    volumes:
      - /var/www/dev.araozu/:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev_araozu.rule=Host(`araozu.dev`)"
      - "traefik.http.routers.dev_araozu.entrypoints=websecure"
      - "traefik.http.routers.dev_araozu.tls=true"
      - "traefik.http.routers.dev_araozu.tls.certresolver=hetzner-resolver"
      - "traefik.http.routers.dev_araozu.tls.domains[0].main=araozu.dev"
      - "traefik.http.routers.dev_araozu.tls.domains[0].sans=*.araozu.dev"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true

